# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      linux_64_:
        CONFIG: linux_64_
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: linux_64_
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
      linux_aarch64_:
        CONFIG: linux_aarch64_
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: linux_aarch64_
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64
      linux_ppc64le_:
        CONFIG: linux_ppc64le_
        UPLOAD_PACKAGES: 'True'
        SHORT_CONFIG: linux_ppc64le_
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
  - script: |
        artifact_name="conda_artifacts_$(build.BuildId)_$(CONFIG)"
        if [[ ${#artifact_name} -gt 80 ]]; then
          artifact_name="conda_artifacts_$(build.BuildId)_$(SHORT_CONFIG)"
        fi
        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
        if [ -d build_artifacts ]; then
          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
          rm -rf build_artifacts/src_cache
        fi
    displayName: Check for conda build artifacts
    condition: succeededOrFailed()

  - task: ArchiveFiles@2
    displayName: Make archive of conda build artifacts
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')
    inputs:
      rootFolderorFile: build_artifacts/
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME).zip
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: Store conda build artifacts
    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/$(ARTIFACT_NAME).zip
      artifactName: $(ARTIFACT_NAME)